auth:
  strategy: anonymous # Bypass login for local development
login_token:
  signing_key: "static-gitops-key-12345" # you wouldn't do this in production, you would use a secret and set: signing_key_secret_name: "kiali-managed-secrets"
external_services:
  prometheus:
    # Points to the Prometheus service created by kube-prometheus-stack
    url: "http://prometheus-kube-prometheus-prometheus.observability.svc.cluster.local:9090"
  grafana:
    enabled: true
    # Points to your Grafana service
    url: "http://prometheus-grafana.observability.svc.cluster.local:80"
  tracing:
    enabled: true
    provider: "jaeger"
    in_cluster_url: "http://jaeger-query.observability.svc.cluster.local:16686"