apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default-strict
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: argocd-permissive
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  mtls:
    mode: PERMISSIVE